### PR TITLE
Add HTTP01-Challenge routes to the ingress

### LINKED ISSUE #416: Renewing the certificate doesn't work as expected and it will call user ksvc for 30 days
We are using cert-manager to manage ksvc certificates and I’ve noticed a weird behaviour.

Be default, cert-manager will create a certificate that will expire in 90 days, then it will try to renew it 30 days before the expiration date.

In this period and when the renew workflow is launched by cert-manager, the certificate is always in `True` state and there is no route in the ingress (we are using Kourier) is configured to forward the traffic `/.well-known/acme-challenge` coming from Lets-encrypt to `cm-acme-http-solver-xxx` pod, so all traffic is instead forwarded to the ksvc pod.

If I understand the [code of net-certmanager](https://github.com/knative-sandbox/net-certmanager/blob/main/pkg/reconciler/certificate/certificate.go#L111) correctly, we are only watching the state of the certificate, and since the certificate is in `True` state, the knative ingress will never be updated so no route will be configured

I'm opening a PR addressing this issue but I'm not `100%` sure that it will work. To reproduce the behaviour we need to wait for 60 days for the renewal process to be lanched (unless there is a workaround for that)

### PR DESCRIPTION
**Pull request by RamyChaabane**
# Changes

:bug: Fix Certificate renewal

Most of the changes in this PR are related to dependencies. I've changed the following:
- pkg/reconciler/certificate/certificate.go
- pkg/reconciler/certificate/controller.go

I've added Knative serving to access the `MakeACMEIngressPaths` function. We could also copy-paste and adapt the relevant code if we want to avoid this dependency

/kind bug

Fixes #416 

**Release Note**

```release-note
fix certificate renewal
```

### CODE REVIEW

**Comment by RamyChaabane** [comment]
Hello @nak3 
This is another patch for Certificate renewal.
This is will reconfigure the ingress to add http01 challenge routes and remove them when the certificate will be renewed.

If you are happy with this, I can add some unit tests

**Comment by tendant** [comment]
Any update on the patch? It will be great to have this merged. A Let'scrypt certificate is valid only for 90 days. Every time it become expired, we have to remove service and reinstall it to get it to work. 

This introduces downtime to all published knative services using let's crypt certificate.

**Comment by dprotaso** [comment]
Quick scan - we don't want `net-certmanager` to be programming the Ingress and pulling in these dependencies. 

There already exists a mechanism to pass the challenge details via the Certificates `Status.HTTP01Challenges` and the Serving Route controller will add the ACME Paths to the Ingress.

It just seems the Route controller doesn't handle a cert renewal case when the Cert is already ready.
https://github.com/knative/serving/blob/a4fcb9dcf510f274dcb13e92d39595047e0b8e0a/pkg/reconciler/route/route.go#L242-L246

Let's regroup on the issue #416

**Comment by dprotaso** [comment]
Going to close this out - as we'll handle the renewing logic in the route controller - there's a WIP here: https://github.com/knative/serving/pull/13666

**Pull request closed without merging**
