### PR TITLE
Rebased #472: Set Certificate.Spec.Domain as commonName

### PR DESCRIPTION
**Pull request by dprotaso**
Rebased: https://github.com/knative-sandbox/net-certmanager/pull/472

### CODE REVIEW

**Comment by dprotaso** [comment]
Testing changes in serving - https://github.com/knative-sandbox/net-certmanager/pull/478

**Comment by dprotaso** [comment]
OK - I confirmed the changes work with a long domain name :)

**Comment by dprotaso** [comment]
weird dns
> dial tcp: lookup http01-conformance-http01-dulfigmm.knative-test.dev on 10.12.0.10:53: no such host

**Comment by KauzClay** [comment]
> weird dns
> 
> > dial tcp: lookup http01-conformance-http01-dulfigmm.knative-test.dev on 10.12.0.10:53: no such host

I wonder if that is because of childName here: https://github.com/knative-sandbox/net-certmanager/pull/478/files#diff-71f7802c8b209384945425e686dc7eb367a0c9f21a84ee5f13aff8146be6082bR59

**Comment by dprotaso** [comment]
These domains never worked - the HTTP01 conformance test just checks that the challenges are set on the certificate - but doesn't do a full round trip test

So the test here need to be updated

https://github.com/knative/networking/blob/4ccbe609c589189f2f0f3f60a3e7babbbf497e31/test/conformance/certificate/http01/certificate.go#L42-L47

**Pull request merged**
