### PR TITLE
[release-1.10] go back to using short prefix on domain (#551)

### PR DESCRIPTION
**Pull request by dprotaso**
cherry pick of #551

The logic to address long domain names didn't work - so we're falling back to what we did in 1.9 (but not scanning all certs)

### CODE REVIEW

**Comment by nak3** [comment]
Do we need to fix `Verify / verify / Verify Deps and Codegen (pull_request)` ?
Otherwise, LGTM.

**Comment by dprotaso** [comment]
> Do we need to fix `Verify / verify / Verify Deps and Codegen (pull_request)` ? Otherwise, LGTM.

done

**Pull request merged**
